Add initial settings support
lirios/browser pull request #17
Opened 2016-11-26 13:25 UTC by tim-sueberkrueb

See #2. 
Implementing sub category urls and/or supporting searching through the settings doesn't make much sense right now due to the lack of many different settings. Those features will be implemented when necessary.

2016-12-02 19:53 UTC, plfiorini requested changes

2016-12-02 19:53 UTC, plfiorini commented on src/core/core.pri
> +    $$PWD/settings/startconfig.cpp
nitpick: if you end this line with a slash future changes will look better in the diff, in HEADERS too

2016-12-02 19:53 UTC, plfiorini commented on src/core/settings/searchconfig.h
> +    explicit SearchConfig(QObject *parent = 0);
use Q_NULLPTR instead of 0

2016-12-02 19:53 UTC, plfiorini commented on src/core/settings/settings.cpp
> +    QString searchEngineString;
it would be better if search engines could be loaded from a data file, this would allow users to install another engine later on.

2016-12-03 10:00 UTC, tim-sueberkrueb commented on src/core/settings/searchconfig.h
> +    explicit SearchConfig(QObject *parent = 0);
@plfiorini using `nullptr` as per Slack conversation. Done in https://github.com/lirios/browser/commit/55ab2a0e484c4a5c069133e4b7807edd5e9dd1f0.

2016-12-03 10:43 UTC, plfiorini approved these changes

2016-12-03 10:45 UTC, plfiorini commented on src/core/core.pri
> +    $$PWD/settings/searchconfig.h
end with \ so every time you make a change adding or removing a file the diff will only show that line

2016-12-03 10:47 UTC, plfiorini requested changes

2016-12-03 10:47 UTC, plfiorini commented on src/core/settings/searchconfig.cpp
> +SearchConfig::SearchConfig(QObject *parent) : QObject(parent)
style: move : QObject(parent) to a new line and indent

2016-12-03 10:53 UTC, plfiorini requested changes

2016-12-03 10:53 UTC, plfiorini commented on src/core/core.pri
> +    $$PWD/settings/searchconfig.h
end with \

2016-12-03 10:53 UTC, plfiorini commented on src/core/core.pri
> +    $$PWD/settings/searchconfig.cpp
end with \

2016-12-03 10:53 UTC, plfiorini commented on src/core/models/tab.h
> +    explicit Tab(QObject *parent = nullptr, bool invalid=false);
style: bool invalid = false

2016-12-03 10:53 UTC, plfiorini commented on src/core/settings/settings.cpp
> +
close the file

2016-12-03 10:53 UTC, plfiorini commented on src/core/settings/settings.cpp
> +    setDirty(false);
close the file

2016-12-03 10:53 UTC, plfiorini commented on src/ui/tabview/TabType.qml
> +        else {
style: } else {

2016-12-03 10:53 UTC, plfiorini commented on src/ui/tabview/content/SettingsContent.qml
> +            margins: 16
Units.largeSpacing instead of 16

2016-12-03 10:54 UTC, tim-sueberkrueb commented on src/core/settings/settings.cpp
> +    QString searchEngineString;
@plfiorini see https://github.com/lirios/browser/issues/22

2016-12-03 11:54 UTC, tim-sueberkrueb commented on src/core/settings/settings.cpp
> +
Done in https://github.com/lirios/browser/pull/17/commits/c1158874f5a04893269e4a553528ee58ab2ebd46

2016-12-03 11:54 UTC, tim-sueberkrueb commented on src/core/settings/settings.cpp
> +    setDirty(false);
Done in https://github.com/lirios/browser/pull/17/commits/c1158874f5a04893269e4a553528ee58ab2ebd46

2016-12-03 11:56 UTC, tim-sueberkrueb commented on src/core/settings/searchconfig.cpp
> +SearchConfig::SearchConfig(QObject *parent) : QObject(parent)
Done in https://github.com/lirios/browser/pull/17/commits/f8b4bf77a577ca41086f8dc7c28524a4bcb0505c

2016-12-03 16:24 UTC, tim-sueberkrueb commented on src/ui/tabview/content/SettingsContent.qml
> +            margins: 16
Done in https://github.com/lirios/browser/pull/17/commits/95513c7897debff95de4199985f2ff8166e8812a

2016-12-06 19:51 UTC, plfiorini approved these changes

2016-12-07 12:28 UTC, merged