Add theme color support
lirios/browser pull request #25
Opened 2017-01-04 15:07 UTC by tim-sueberkrueb

See #14.
Note that the settings and a lot of the structure will change with `feature/extensions` (see #22).
But since there is no release yet, this shouldn't really matter.

2017-01-04 15:35 UTC, plfiorini requested changes

2017-01-04 15:35 UTC, plfiorini commented on src/core/settings/settings.h
> +<<<<<<< e738755cea07dcb93be91605a6bab4a62d702c10
merge garbage here :D
please fix

2017-01-04 15:35 UTC, plfiorini commented on src/ui/tabview/content/SettingsContent.qml
> +                    text: "Adapt to website theme colors"
use qsTr()

2017-01-04 15:35 UTC, plfiorini commented on src/core/models/tab.cpp
> +    m_iconColor = QColor("transparent");
Qt::transparent, I think it might be more efficient

2017-01-04 15:35 UTC, plfiorini commented on src/ui/tabview/content/SettingsContent.qml
> +                        text: "Adapt to website theme colors"
qsTr

2017-01-04 16:23 UTC, tim-sueberkrueb commented on src/core/settings/settings.h
> +<<<<<<< e738755cea07dcb93be91605a6bab4a62d702c10
oh no xD

2017-01-04 16:23 UTC, tim-sueberkrueb commented on src/core/settings/settings.h
> +<<<<<<< e738755cea07dcb93be91605a6bab4a62d702c10
Will fix

2017-01-04 16:33 UTC, tim-sueberkrueb commented on src/core/settings/settings.h
> +<<<<<<< e738755cea07dcb93be91605a6bab4a62d702c10
Fixed.

2017-01-04 16:34 UTC, tim-sueberkrueb commented on src/ui/tabview/content/SettingsContent.qml
> +                        text: "Adapt to website theme colors"
See #13 :) Right now, no string in the browser is translatable.

2017-01-04 16:35 UTC, tim-sueberkrueb commented on src/core/models/tab.cpp
> +    m_iconColor = QColor("transparent");
Done

2017-02-07 23:16 UTC, plfiorini approved these changes

2017-02-12 10:35 UTC, merged