Drop SlimeEngine
lirios/browser pull request #56
Opened 2017-05-05 13:42 UTC by tim-sueberkrueb

Drop SlimeEngine and switch to using QtWebEngine only.
See #40.

2017-05-06 18:33 UTC, plfiorini requested changes
seems good but i haven't tried building it, i assume it does :)

2017-05-06 18:33 UTC, plfiorini commented on .gitmodules
> +	url = https://github.com/lirios/qmake-features
use `git://github.com/lirios/qmake-feature.git` since it's faster than https

2017-05-07 10:19 UTC, plfiorini approved these changes

2017-05-07 10:20 UTC, tim-sueberkrueb commented
Huh, travis fails now.

2017-05-07 10:21 UTC, tim-sueberkrueb commented
Damn, copied the wrong url, sorry for that.

2017-05-07 10:29 UTC, tim-sueberkrueb commented
Okay, thanks @plfiorini. If we find any unnecessary/leftover QML wrapper code in the future, I think we can just simplify/fix it on `develop`.

2017-05-07 10:30 UTC, merged

2017-05-07 10:33 UTC, plfiorini commented
@tim-sueberkrueb yep